version: '3.5'
services:
  consul:
    image: consul:latest
    container_name: consul_server
    volumes:
      - consul_data:/consul/data
    ports:
      - 8300:8300
      - 8301:8301
      - 8500:8500
      - 8600:8600
    command: "consul agent -server -bootstrap -ui -client=0.0.0.0 -data-dir=/consul/data"
    networks:
      - dms_sms_local

volumes:
  consul_data:
    name: consul_data
    driver: local

networks:
  dms_sms_local:
    name: dms_sms_local
    driver: bridge