version: '3.5'
services:
  consul:
    image: consul:latest
    container_name: consul_server
    volumes:
      - consul_data_1:/consul/data
      - ./consul-conf.json:/consul/conf/consul-conf.json
    ports:
      - 8300:8300
      - 8301:8301
      - 8500:8500
      - 8600:8600
    command: "consul agent -server -bootstrap -ui -client=0.0.0.0 -bind=127.0.0.1 -data-dir=/consul/data"
    networks:
      - dms-sms-local
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=consul]

volumes:
  consul_data_1:
    name: consul_data_1
    driver: local

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: overlay
