version: '3.5'
services:
  jaeger:
    container_name: jaeger_server
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - dms-sms-local

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: bridge