version: '3.5'
services:
  jaeger:
    container_name: jaeger_server
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - dms-sms-local
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_TAGS_AS_FIELDS_ALL=true
      - ES_NUM_SHARDS=1
      - ES_NUM_REPLICAS=1
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=jaeger]

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: overlay