apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ./jaeger_docker_compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  ports:
    - name: "16686"
      port: 16686
      targetPort: 16686
      protocol: TCP
    - name: "6831"
      port: 6831
      targetPort: 6831
      protocol: UDP
  selector:
    io.kompose.service: jaeger
status:
  loadBalancer: {}
