version: '3.5'

services:
  proxy:
    image: nginx:latest
    deploy:
      mode: global
      labels: [APP=nginx]
#      constraint:
#        - node.role == worker
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - target: 81
        published: 81
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - dms-sms-local

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: overlay
