version: '3.5'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - dms-sms-local
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=mysql]

volumes:
  db_data:
    name: db_data
    driver: local

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: overlay
