version: '3.5'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dev_server
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - dms_sms_local
    ports:
      - 3306:3306

volumes:
  db_data:
    name: db_data
    driver: local

networks:
  dms_sms_local:
    name: dms_sms_local
    driver: bridge