version: '3.5'

services:
  logstash:
    container_name: logstash
    image: logstash:7.9.3
    ports:
      - 5044:5044
    volumes:
      - ./logstash.conf:/conf-dir/logstash.conf
    command: logstash -f /conf-dir/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - dms-sms-local
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=logstash]

  kibana:
    container_name: kibana
    image: kibana:7.9.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://DSM-SMS-elasticsearch:9200
    depends_on:
      - dms-sms-local
    networks:
      - dms-sms-local
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=kibana]


volumes:
  elasticsearch:
    name: elaticsearch
    driver: local

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: overlay
