apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f mongo_docker_compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f mongo_docker_compose.yml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/dms-sms-local: "true"
        io.kompose.service: mongo
    spec:
      containers:
        - image: mongo:3.6.21
          name: mongo-server
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-db-data
      restartPolicy: Always
      volumes:
        - name: mongo-db-data
          persistentVolumeClaim:
            claimName: mongo-db-data
status: {}
