version: '3.5'

services:
  mongo:
    image: mongo:3.6.21
    container_name: mongo_server
    volumes:
      - mongo_db_data:/data/db
    networks:
      - dms-sms-local
    ports:
      - 27017:27017

volumes:
  mongo_db_data:
    name: mongo_db_data
    driver: local

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: bridge
