version: '3.5'

services:
  mongo:
    image: mongo:3.6.21
    container_name: mongo_dev_server
    volumes:
      - mongo_db_data:/data/db
    networks:
      - dms_sms_local
    ports:
      - 27017:27017

volumes:
  mongo_db_data:
    name: mongo_db_data
    driver: local

networks:
  dms_sms_local:
    name: dms_sms_local
    driver: bridge