version: '3.5'

services:
  redis:
    image: redis:latest
    container_name: redis_server
    networks:
      - dms-sms-local
    volumes:
      - redis_data:/var/lib/redis
      - redis_log:/redis.log
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=redis]

volumes:
  redis_data:
    name: redis_data
    driver: local
  redis_log:
    name: redis_log
    driver: local

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: bridge
