version: '3.5'

services:
  redis:
    image: redis:latest
    container_name: redis_server
    networks:
      - dms-sms-local
    ports:
      - 6379:6379

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: bridge
