version: '3.5'

services:
  mongo:
    image: redis:latest
    container_name: redis_dev_server
    networks:
      - dms_sms_local
    ports:
      - 6379:6379

networks:
  dms_sms_local:
    name: dms_sms_local
    driver: bridge